USE [master]
GO

/****** Object:  Database [LibraryConsole]    Script Date: 4/26/2022 4:32:48 PM ******/
CREATE DATABASE [LibraryConsole]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'LibraryConsole', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LibraryConsole.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'LibraryConsole_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\LibraryConsole_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [LibraryConsole].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [LibraryConsole] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [LibraryConsole] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [LibraryConsole] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [LibraryConsole] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [LibraryConsole] SET ARITHABORT OFF 
GO

ALTER DATABASE [LibraryConsole] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [LibraryConsole] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [LibraryConsole] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [LibraryConsole] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [LibraryConsole] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [LibraryConsole] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [LibraryConsole] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [LibraryConsole] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [LibraryConsole] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [LibraryConsole] SET  DISABLE_BROKER 
GO

ALTER DATABASE [LibraryConsole] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [LibraryConsole] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [LibraryConsole] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [LibraryConsole] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [LibraryConsole] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [LibraryConsole] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [LibraryConsole] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [LibraryConsole] SET RECOVERY FULL 
GO

ALTER DATABASE [LibraryConsole] SET  MULTI_USER 
GO

ALTER DATABASE [LibraryConsole] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [LibraryConsole] SET DB_CHAINING OFF 
GO

ALTER DATABASE [LibraryConsole] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [LibraryConsole] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [LibraryConsole] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [LibraryConsole] SET QUERY_STORE = OFF
GO

ALTER DATABASE [LibraryConsole] SET  READ_WRITE 
GO


